### ISSUE TITLE
Feature request: Button to create additional Resources.

### ISSUE THREAD

**Issue by theelous3** [Sky-Captain-13/foundry#14]
It's not uncommon to have more than three resources. I would like the ability to create additional resources, ideally through a `+` button, that creates one additional resource.

**Comment by Bogus73** [comment]
I really like the sheet. Just to add an idea to this. Is there a way to add aplus/minus button to resources? As you use it (second wind for example) you could just hit the minus button and be done. As is you have to klick the number and change it.

**Comment by Sky-Captain-13** [comment]
There's a module for adding more resources.

https://foundryvtt.com/packages/resourcesplus/
