### ISSUE TITLE
Points of Interest incompatible with PF2?

### ISSUE THREAD

**Issue by dd8630** [Sky-Captain-13/foundry#15]
The sheet looks excellent, but it doesn't seem to work with PF2 - is there any way to let it work? I've tried tinkering with the code but I'm honestly out of my depth! If this could work with the Pathfinder 2e system that'd be amazing.

**Comment by Sky-Captain-13** [comment]
It is a 5e sheet only. Someday I will get around to making it a base actor sheet option.
