### ISSUE TITLE
Powercards not compatible with The Furnace's Avanced Macros

### ISSUE THREAD

**Issue by Norc** [Sky-Captain-13/foundry#16]
Test Info (latest everything): Foundry 0.6.0 on Windows 10 self hosted (electron app as GM), DND5e 0.92, Powercards 0.0.7, Furnace 1.8. 

I know that Powercards is far down your list of concerns, but the lack of compatibility with The Furnace's Advanced Macros makes it basically unusable for me and many others. The Advanced Macros of The Furnace are basically a dependency for several other modules.

If I uncheck the Advanced Macros configuration, the following powercard (intended for the 5E Rogue's Assassin 3rd level ability) displays beautifully:

![image](https://user-images.githubusercontent.com/64667579/83270760-eeb18880-a196-11ea-82bf-c83ec938cbdc.png)

```
//not compatible with Furnace Advanced Macros!!

!power {{
--emote|Surprise, MFer.
--title|Surprise
--title_fontsize|1.5em
--title_txcolor|#FFFFFF
--title_bgcolor|#8B0000
--subtitle|Ranged * Range (80/320)
--Attack:|[[1d20 + 4]] | [[1d20 + 4]] vs AC
--Damage:|[[2d6+6d6+4]] critical hit piercing damage
}}

```
If I enable the Advanced macros checkbox, I instead get this error for the same macro:
![image](https://user-images.githubusercontent.com/64667579/83270433-734fd700-a196-11ea-8e1e-9822c80e6c89.png)

Any help would be greatly appreciated :(

**Comment by Norc** [comment]
After discussing with Sky, closing and will take it up with the author of The Furnace module.

**Comment by Norc** [comment]
Sky, good news. @rücklicht (Frerk)#0985  on FVTT discord had a pro-tip that set me in the right direction. Swapping out the {{ }} for a single set of brackets {} bypassed the issue with The Furnace Advanced macros, and still allows Powercards to function. Problem solved!

**Comment by Sky-Captain-13** [comment]
Likely just a coincidence with the difference between Foundry sending the contents of the macro/chat as a single entity versus Roll20 (which powercards was originally written for) sending them line by line for multi-line processing. If Foundry ever changes to multi-line processing, the lack of curly braces or a single set will break any powercard macros that rely on them.
