### ISSUE TITLE
Feature Request (alt-5e): attack/damage roll button

### ISSUE THREAD

**Issue by ardittristan** [Sky-Captain-13/foundry#17]
On the default sheet, the favorite item tab module has buttons to roll for damage/attack
![image](https://user-images.githubusercontent.com/42787508/83331636-8a2a2280-a297-11ea-9ceb-d7b56757db70.png)

would it be possible to add the same to the favorites list of this sheet?

**Comment by Sky-Captain-13** [comment]
Not really something I'm interested in adding since I will never not use Better Rolls.
