### ISSUE TITLE
Dice are not rolled

### ISSUE THREAD

**Issue by muehf** [Sky-Captain-13/foundry#18]
I created the following macro:
/roll 1d20+?{Modifier|4}

It kind of works as desired but the dice are not rolled. I simply get a chat message saying:
/roll 1d20+4

Do you know what Im doeing wrong or is this a bug?
foundaryvtt v0.6.0
query 0.0.4

**Comment by Sky-Captain-13** [comment]
Query only works using inline rolls at the moment.

**Comment by muehf** [comment]
Ok, thanks for the answer. Working with makros would be a highly desired feature for me. If this could be implemented I would be very happy!
Thanks for your work!

**Comment by Sky-Captain-13** [comment]
You could just do **[[1d20 + ?{Modifier|0}]]** instead.
