### ISSUE TITLE
Hardcoded strings on character sheet

### ISSUE THREAD

**Issue by Kheldarek** [Sky-Captain-13/foundry#19]
Some string on character sheet are hardcoded in html file. Any chance you could do localised strings to support translation? This card is great, i am translating 5e to polish on my foundry server, i would like to be able to have it fulli in polish :).

**Comment by Kheldarek** [comment]
I hope you see this :) I am talking about words like "Core", "Private Notes", "Ability Scores" in alt5e-sheet.html

**Comment by Sky-Captain-13** [comment]
Alt5e is no longer actively being developed for Foundry. I have switched to using Tidy5e.
