### ISSUE TITLE
New 5e system update bug

### ISSUE THREAD

**Issue by ardittristan** [Sky-Captain-13/foundry#20]
With the new 5e update some parts of the sheet overlap with each other.
![image](https://user-images.githubusercontent.com/42787508/84604572-3292d600-ae97-11ea-8ba2-635e8467408d.png)
![image](https://user-images.githubusercontent.com/42787508/84604578-42aab580-ae97-11ea-9df6-4c6557a95d54.png)

**Comment by Sky-Captain-13** [comment]
This is fixed now.
