### ISSUE TITLE
Alt 5E character sheet not showing in list of modules during game.

### ISSUE THREAD

**Issue by Tynoshi** [Sky-Captain-13/foundry#23]
Hello!

I love this mod to the FoundryVTT character sheet. My campaign has been using it for a few sessions now, but after the recent update it won't show up in my list of modules anymore. Before launching the world, I have checked for most recent updates and made sure they're installed. After launching the world, when I look at module settings nothing shows up and everyone has been reverted to the default foundry character sheet. How can I fix this issue?

Thank you for the awesome mod!

**Comment by Tynoshi** [comment]
To clarify, it isn't showing up when I click 'Manage Modules' anymore, and nothing I do seems to help me re-integrate it into the game. (I've even tried uninstalling and reinstalling.

Alternate 5e Sheet version: 1.3.2
Foundry version: 0.6.2

**Comment by Tynoshi** [comment]
Welp, I discovered the issue was that I needed to update the Game system for Dnd 5e. Everything is working now. So, Foundry, Modules, and Game Systems need to be update together. Sorry to disturb and thanks again for the awesome mod! :)

**Comment by Sky-Captain-13** [comment]
Yeah... I added a minimumSystemVersion to module.json with the expectation that it wouldn't allow you to upgrade the module or something.
