### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by DamondSD** [Sky-Captain-13/foundry#24]
I, and my players, have very much enjoyed using your Alternate 5e sheet, but now for some reason it has vanished from my manage modules page.  I have uninstalled it, reinstalled it, updated it...  It's says it is there and up to date, yet it is not showing on the management page.

**Comment by Sky-Captain-13** [comment]
You need to up date your 5e system. Alt5e is only compatible with the most recent update to the D&D system (0.93).
