### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by QuelessQuest** [Sky-Captain-13/foundry#27]
A general version that does not require dnd5e. I love the idea of this module, but am not a dnd5e user.

**Comment by SalieriC** [comment]
Me neither and it still works... Have you tried if another module might be incompatible?

**Comment by Sky-Captain-13** [comment]
Change the version of Token Tooltip to 9.9.9 and change the stats to something else. I only play D&D 5e and will only support D&D 5e.
