### ISSUE TITLE
new "point of interest" actor and settings not available

### ISSUE THREAD

**Issue by PalaNolho** [Sky-Captain-13/foundry#31]
I installed the "Point of Interest Character Sheet" and activated the module, but I don't see any module configurations in the module settings nor I see any new type of actor (or sheet template) when creating/configuring an actor.

In case it's relevant, I'm using `Foundy v0.6.6` and `DnD5e - Fifth Edition System v0.9.6`

**Comment by miguel-pinto-prodmad** [comment]
I found out where it was. It was just available for Actor handouts

**Comment by miguel-pinto-prodmad** [comment]
This issue can be closed
