### ISSUE TITLE
Feature Request: Defense Rolls and Saving Attacks

### ISSUE THREAD

**Issue by Biggoron144** [Sky-Captain-13/foundry#33]
https://giffyglyph.com/darkerdungeons/rules/active_defense.html
https://media.wizards.com/2015/downloads/dnd/UA5_VariantRules.pdf
It'd be neat to have the option to enable 'Players Make All Rolls' mode a la 3.5e. The idea would be to click on your AC and spellcasting DC to roll defense checks and saving attacks, respectively. To be clear, the UA actually has improper math compared to the Darker Dungeons version,, but I included it as it's official 5e playtest stuff.

**Comment by Sky-Captain-13** [comment]
I have no interest in supporting this. If it gets added to the official sheet, it would carry over to Alt5e.
