### ISSUE TITLE
Dragging an item using Alt5e and Foundry 0.7.5 causes errors

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [Sky-Captain-13/foundry#36]
Dragging an item using the mouse (while pressing a mouse button, pressed all the time) on the sheet causes the following 2 errors:

````alt5e.js:215 Uncaught TypeError: app._onDragItemStart is not a function
    at HTMLLIElement.handler (alt5e.js:215)
handler @ alt5e.js:215

VM957:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLLIElement.<anonymous> (alt5e.js:239)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)
````

Versions:
Foundry: 0.7.5
Alt5e:
DnD5e: 0.98

Modules:
about-time
alt5e
animated-spell-effects
betterCurses
betternpcsheet5e
blind-roll-skills
coloredeffects
colorsettings
combat-utility-belt
compendium-folders
conditions5e
custom-hotbar
custom-nameplates
dae
dice-calculator
dice-so-nice
difficultterrain
Dynamic-Effects-SRD
easy-target
forien-copy-environment
forien-quest-log
forien-scene-navigator
foundry_community_macros
furnace
gm-notes
illandril-chat-enhancements
illandril-hotbar-uses
illandril-token-hud-scale
lootsheetnpc5e
macroeditor
maestro
max-crit
michaelghelfi
midi-qol
modules.txt
npc-chatter
permission_viewer
pings
popout
README.txt
ShowArtwork
target-enhancements
TerrainLayer
token-action-hud
TokenHotbar
tokenmagic
torch
turnAlert
workshop-welcome-screen

**Comment by Sky-Captain-13** [comment]
I didn't write that section. It's from FavTab... I'll have to either just remove it or get some help adding sorting back in.

**Comment by Sky-Captain-13** [comment]
Oops. Forgot to mark this closed. It has been fixed.
