### ISSUE TITLE
Death rolls checkboxes don't work

### ISSUE THREAD

**Issue by DarKDinDoN** [Sky-Captain-13/foundry#4]
Hi, thx for this great alternative to the basic sheet.
When a character is rolling death saves, the checkboxes are not updated.

**Comment by Sky-Captain-13** [comment]
Yeah... I know. They're manual check only right now. Haven't had time to figure out how to sync them with the actual death saves tracking data. The checkboxes and clicking to roll death saves were something I added before they were on the core sheet.

**Comment by Sky-Captain-13** [comment]
Removed them since I had made no progress towards syncing the core data and the checkboxes.
