### ISSUE TITLE
Attunement Symbol on Created Items

### ISSUE THREAD

**Issue by AndreasHVRC** [Sky-Captain-13/foundry#40]
Items created will not have the attunement symbol next to their name, even tho Attuned/Attunment required is selected in the Item Sheet
Created Item
![image](https://user-images.githubusercontent.com/18007652/102892766-a7575600-4460-11eb-879d-d11de64197b8.png)
Imported Item
![image](https://user-images.githubusercontent.com/18007652/102892818-be964380-4460-11eb-829c-fc24b1cc79c0.png)

After doing some digging through the html code, i found the name tag required to set the symbol is "item.data.attuned" (templates/parts/alt5e-inventory.html, line 63). When an item is created or imported the name label seems to be "data.attunement".
![image](https://user-images.githubusercontent.com/18007652/102893230-7f1c2700-4461-11eb-8574-33b6aad90251.png)

Our group is really enjoying your mod and thank you for your time and effort invested into this.
Greetings AndreasH

**Comment by Sky-Captain-13** [comment]
Ah yeah. Atropos changed the data behind attuned items recently. I haven't really had any items to attune in the games I play in, so it hadn't come up. Will get a fix out soon.

**Comment by neffers-gridcoin** [comment]
I replaced line 63 with these two lines:

`								{{~#if (eq data.attunement 2)}} <i class="fas fa-sun attuned" title={{localize "DND5E.Attuned"}}></i>{{/if}}
								{{~#if (eq data.attunement 1)}} <i class="fas fa-sun not-attuned" title={{localize "DND5E.AttunementRequired"}}></i>{{/if}}`

To allow me to distinguish between an Attuned item and one that can be attuned but isn't.

**Comment by Sky-Captain-13** [comment]
Alt5e is no longer being actively worked on for Foundry. I have switched to using Tidy5e for my campaigns.
