### ISSUE TITLE
[Improvement] [alt5e] Attuned items counter

### ISSUE THREAD

**Issue by MrPadRpg** [Sky-Captain-13/foundry#41]
Hi,

I don't know if you take request for new features (if not, you can close this ticket) but it would be nice to have a counter for the attuned items.
Some players have a ton of items, many of them requires attunement, and sometime, they lost the count.
Kind like the counter for the prepared spells.

Thanks.

**Comment by Sky-Captain-13** [comment]
Alt5e is no longer being actively worked on for Foundry. I have switched to using Tidy5e for my campaigns.
