### ISSUE TITLE
Sheet is broken in 0.8.6

### ISSUE THREAD

**Issue by DivertedCircle** [Sky-Captain-13/foundry#47]
Module appears to be broken in the 0.8.6 update. Any text entered is not displaying when you open the sheet.

Foundry Version 0.8.6
DnD5e Version 1.3.3
POI Sheet Version 0.0.8

**Comment by RavenknightDM** [comment]
Aw. :( I was afraid of that.

**Comment by Sky-Captain-13** [comment]
I'll see if I can get a quick update on the PoI sheet. I really should just make it systemless and less prone to breakage.

**Comment by RavenknightDM** [comment]
Sounds great, Sky.

**Comment by Sky-Captain-13** [comment]
I potentially have a fix... but I don't have a way to test whether it works on existing PoI tokens or if I need to create some kind of data migration script.

**Comment by Sky-Captain-13** [comment]
Should be fixed... as always... MAKE BACKUP COPIES.
