### ISSUE TITLE
Is it possible to invoque a querry form a rolltable?

### ISSUE THREAD

**Issue by Muji-k** [Sky-Captain-13/foundry#48]
Hi , I'm trying to use query to make a variable modifier to a rolltable formula, the formula that I'm using is 2d6+?{Reaction modifier|}
but it doesn't seem to work, the rolltable is unable to make the roll  if query is used (nothing happens when i press the roll button), is there a way around this?

**Comment by Sky-Captain-13** [comment]
Query is not really well supported at all. It was mostly me just trying something and failing. Sorry.

**Comment by Muji-k** [comment]
No problem, actually i really like your module, in my opinion it can be a good way to accomplish some things in foundry. There is no need to apologize, and I wish i had the capacity to code something other than a Hello World! script. Thanks for your work.
