### ISSUE TITLE
Not an Issue BUT

### ISSUE THREAD

**Issue by Luthervian** [Sky-Captain-13/foundry#49]
Hi, i absolutely love the map image you used in your example image for this module on FoundryVTT-hub. I have fallen in love with the style. What software did you use for this? I'd like to throw money at it. :)

**Comment by Sky-Captain-13** [comment]
http://www.uniwar.com/assets/game/index.html

I made the tiles using the files at that link. I've tried getting ahold of the company through their email address, so I could ask if I could post a link to the hex tiles somewhere... but haven't got any word back from them.
