### ISSUE TITLE
Deselection: not a GM feature only

### ISSUE THREAD

**Issue by DarKDinDoN** [Sky-Captain-13/foundry#5]
Hi, not sure if normal. But in the Deselection Readme, it is written that it's a GM only feature. It appears to be available for players as well.

**Comment by Sky-Captain-13** [comment]
Yeah... it's intended to work for both GM's and players. I just forgot to update the readme.

**Comment by DarKDinDoN** [comment]
Ok. Maybe make it an option for the players. For example, playing with DnD system requires the player to select the token to use the macros.

**Comment by Sky-Captain-13** [comment]
That's not going to stop them from being able to deselect their token. They can still draw an empty selection box on the map or hit escape to deselect their tokens.

**Comment by DarKDinDoN** [comment]
Yes you are right. But I sure don't want to make it easy for them to deselect their token when there is not reason to. It's just asking for players to make the same mistake over and over.
