### ISSUE TITLE
[POI Sheet] Compatibility with other systems.

### ISSUE THREAD

**Issue by Priderino** [Sky-Captain-13/foundry#50]
I absolutely love your POI sheet, and I miss it when I'm not playing 5e. I'd love to have it compatible with other systems, like Pathfinder 2e, Call of Cthulu and Tormenta20. It being a generic sheet instead of being 5e only would be greatly appreaciated.

**Comment by EsotericOdyssey** [comment]
I have to second this one, but for Simple Worldbuilding specifically, I run a lot of games that don't have systems of their own in Foundry and this is a module that would help me immensely
