### ISSUE TITLE
Currency borked

### ISSUE THREAD

**Issue by Apockelipse** [Sky-Captain-13/foundry#51]
Currency seems to be borked as it now read:
[object
Object]

for some strange reason.

https://i.imgur.com/OVSmi6W.png

**Comment by ItsZen-EXE** [comment]
I actually just fixed this on my own version.

Here's the steps I took:

First, find your install path for your world, then go to "...\Data\modules\alt5e\templates\parts"

In here should be 4 files, each are a different page on the sheet. Open the "alt5e-inventory.html" in a text editor and near the top, line 11 should be this:
`<label class="denomination {{k}}">{{ lookup ../config.currencies k }}</label>`

Simply change "config.currencies" to "labels.currencies" so it looks like this:

`<label class="denomination {{k}}">{{ lookup ../labels.currencies k }}</label>`

Save and this should fix your issue for now. Maybe make sure to lock the module so it doesnt auto-update till theres an actual fix from the developer, but that should work for now. DnD 5e's system updated and changed the locations it needs to look for things like that.
