### ISSUE TITLE
What Happened to the Expander Module?

### ISSUE THREAD

**Issue by PhluXx1** [Sky-Captain-13/foundry#54]
What Happened to the Expander Module? The page is 404ing and it's missing from the Foundry installer directory.

**Comment by Sky-Captain-13** [comment]
I deleted it. Foundry made a change to where the chat window popped out when you clicked it while the sidebar was minimized and I couldn't get it to not do that. I suggest looking into Monk's Little Details. He has some code/css that moves the expansion arrow to the top of the sidebar when you collapse it.
