### ISSUE TITLE
Unable to delete Items/Features

### ISSUE THREAD

**Issue by Gravydigger** [Sky-Captain-13/foundry#55]
Hello,

When trying to delete an item in a character sheet, it does not remove the item.
![Capture](https://user-images.githubusercontent.com/53815736/147824890-3aae8649-d8f1-4df6-b62b-80ed4ee1b55d.PNG)

Looking at the console, I get this error:
```js
Uncaught ReferenceError: itemId is not defined
[Detected 1 package: alt5e]
    at HTMLAnchorElement.<anonymous> (modules/alt5e/alt5e.js:94)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.v.handle (jquery.min.js:2)
```
The issues appear to be caused by this section in the code in `alt5e.js`, Line 94:
```js
89 // Item Delete Confirmation
90    html.find('.item-delete').off("click");
91    html.find('.item-delete').click(event => {
92      let li = $(event.currentTarget).parents('.item');
93      let itemID = li.attr("data-item-id");
94      let item = this.actor.items.get(itemId);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
```
Did you mean to use the variable `itemID` defined in line 93 instead?

Best regards!

**Comment by kuroyuki13** [comment]
Tested this change locally, and itemID does work.

**Comment by Sky-Captain-13** [comment]
Derp. Sorry... I must have typed it wrong. I'll get a fix out later this afternoon. Thanks!
