### ISSUE TITLE
POI-sheet - Style and Location text misaligned.

### ISSUE THREAD

**Issue by RavenknightDM** [Sky-Captain-13/foundry#58]
Hiya, as always, thanks for the mod.
Just updated to DnD 1.6 and noticed a misalignment with the text on the sheet. The information looks at usual so it's not a big thing.
/Ravenknight
![POI-Sheet-Type](https://user-images.githubusercontent.com/53635985/165792325-7fa7e2ad-dfc7-4e4e-9bd4-68f7629b43f4.png)

**Comment by Sky-Captain-13** [comment]
Thanks. Will try and get this fixed soon. It's likely a result of updating your D&D system to 1.6.x

**Comment by Sky-Captain-13** [comment]
It's fixed. It was literally one little fucking piece of CSS added in ver 1.6.x of the D&D system. Some `margin-inline-start: 4px;` that was the cause. Hate things like that.
