### ISSUE TITLE
alt5e sheet for npcs?

### ISSUE THREAD

**Issue by BuggStream** [Sky-Captain-13/foundry#7]
I really enjoy the alternate sheet you have made, which is why I would think it'd be awesome if I could use a similar sheet for the NPCs.
So is this something that you would want to add in the future?

**Comment by Sky-Captain-13** [comment]
I have some ideas for an Alt5eNPCSheet, but I just haven't had time to get to it yet.

**Comment by Sky-Captain-13** [comment]
Given the existence of the Monsterblocks module for D&D 5e npcs, I won't be creating my own version of an npc sheet.

**Comment by BuggStream** [comment]
> Given the existence of the Monsterblocks module for D&D 5e npcs, I won't be creating my own version of an npc sheet.

Thanks a lot for the tip, will check it out!
