### ISSUE TITLE
No Add Button for Cantrips

### ISSUE THREAD

**Issue by Tmktahu** [Sky-Captain-13/foundry#8]
There doesn't seem to be a `+ Add` button for Cantrips. You can get around the issue by creating a spell in another category and then changing the spell level in the details, but I assume this is not intended?

![](https://i.imgur.com/YJ88ZnW.png)

**Comment by Sky-Captain-13** [comment]
That is a vanilla 5e issue. I don't do anything on the Spellbook tab. Alt5e only alters the main sheet, the Attributes (Core) tab, and the Biography tab. Doesn't touch Inventory, Features, or Spellbook.
