### ISSUE TITLE
TokenTooltip not visible for players

### ISSUE THREAD

**Issue by Norc** [Sky-Captain-13/foundry#9]
Myself and several other players (@gooseman @Daniel on foundry VTT) cannot get the Token Tooltip to be visible for players.  Even with the permissions dropdown set to All Tokens, players can still only see the tooltip for all owned tokens. Tooltip as GM functions normally.

Tested with foundry 0.5.5 with hotfix, DND5E 0.88, and Token Tooltip 1.3.5. No other modules were active.

**Comment by Sky-Captain-13** [comment]
After a bit of looking around, it's because I tried to use `canvasToken.worldTransform.tx` to get the location of the token on the screen and those values aren't visible unless you have control of the token. Gonna have to go back to the drawing board again. >_<

**Comment by Sky-Captain-13** [comment]
Hah! Was able to find a way around that. Will have a fix for it here in a bit.
